/**
 * Regenerates src/docs/Foundation/token-catalog.generated.ts from
 * src/styles/theme.css. Run via `npm run generate:tokens` (wired into predev /
 * prebuild) — never edit the generated file.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseTokenCatalog } from "./lib/token-catalog.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const THEME_CSS = join(__dirname, "..", "src", "styles", "theme.css");
const OUT = join(
  __dirname,
  "..",
  "src",
  "docs",
  "Foundation",
  "token-catalog.generated.ts",
);

const css = readFileSync(THEME_CSS, "utf-8");
const { rows } = parseTokenCatalog(css);

const out = `// AUTOGENERATED by scripts/generate-token-catalog.ts — do not edit.
// Source of truth: src/styles/theme.css (npm run generate:tokens).

export interface TokenRow {
  /** Full custom property name, e.g. "--color-primary". */
  name: string;
  /** Resolved leaf value under light (hex / rgba / keyword). */
  light: string;
  /** Resolved value under dark; falls back to the light value. */
  dark: string;
  /** Bare primitive this token aliases per theme, e.g. "purple-700". */
  mapsToLight?: string;
  mapsToDark?: string;
}

export const TOKEN_CATALOG: TokenRow[] = ${JSON.stringify(rows, null, 2)};
`;

writeFileSync(OUT, out);
console.error(`✓ token catalog generated: ${rows.length} tokens`);
